### ISSUE TITLE
stim_repeat does not seem to work as intended

### ISSUE THREAD

**Issue by lnalborczyk** [jbakermans/stimulus-history-euler-tours#1] opened 2021-11-16 12:43 UTC
Hi, let me first thank you for creating and sharing these functions, they are super helpful! :)

I have been using this package in `R` via the `reticulate` package (which allows using `Python` packages in `RStudio`) and I am a bit puzzled by the `stim_repeat` argument.

My understanding of that argument is that it should prevent successive repetitions of the same "stimulus". For instance, executing `Euler(stimuli = 4, stim_repeat = "False")` should not produce sequences such as `1 2 4 2 3 4 4 1 4 3 3 2 2 1 3 1 1,` which is the sequence I have just obtained... but maybe I have misunderstood the intended role of this argument?

Here is a reproducible example (in `R`, sorry) below, assuming the `euler.py` script is in the current repository.

```
library(reticulate)
set.seed(666)
source_python("euler.py")
experiment <- Euler(stimuli = 4, stim_repeat = "False", pair_repeats = 1)
as.numeric(experiment$get_sequence() )

 [1] 0 0 1 2 2 0 2 3 3 2 1 1 0 3 1 3 0
```

**Comment by jbakermans** [comment] 2021-11-16 15:36
Hi! Very happy to hear it's useful :)
I think you understood the intended role of the stim_repeat argument correctly. I have never run this in R, but I have a suspicion about what's going wrong. The stim_repeat argument expects a Boolean for its value, i.e. `True` or `False`, while the bit of code you posted provides a string, i.e. `"False"`. I think you would get the expected behaviour if you replace `"False"` by `False` - at least when I tried this directly in Python, it did:
Compare
`experiment = euler.Euler(stimuli = 4, stim_repeat = "False", pair_repeats = 1); experiment.get_sequence()`
which gives
`['1', '1', '3', '3', '1', '0', '2', '0', '0', '3', '0', '1', '2', '3', '2', '2', '1']`
to 
`experiment = euler.Euler(stimuli = 4, stim_repeat = False, pair_repeats = 1); experiment.get_sequence()`
which gives
`['2', '0', '2', '1', '2', '3', '1', '3', '0', '1', '0', '3', '2']`

The reason seems to be that, somewhat confusingly, in Python
`bool("False")`
returns
`True`

**Comment by jbakermans** [comment] 2021-11-22 15:37
Closing this now because I think this solves it, but let me know if it doesn't for you!

**Closed as completed by jbakermans** 2021-11-22 15:37 UTC

**Comment by lnalborczyk** [comment] 2021-11-22 20:04
It totally solves it, thank you for the detailed explanation (and sorry for not replying)!
